<?php
	$b_table="admin_user,book,dept,member,member_message,n_article,n_class,n_zxreg";
	$tb[admin_user]=1;
$tb[book]=1;
$tb[dept]=1;
$tb[member]=1;
$tb[member_message]=1;
$tb[n_article]=1;
$tb[n_class]=1;
$tb[n_zxreg]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="sq_hbsst";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	$b_bakdatatype=0;
	?>