<?
 include "include.php";
 $types=$_GET['types'];

 $page_now=$_GET['page_now'];
 if(strlen($page_now)<1){
	 $page_now=1;
 }
 $sql="select * from img where types=1 order by pid";
 $page_recs=12;
 $rec=mysql_query($sql,$conn);
 $total_user=mysql_num_rows($rec);
 $pages=ceil($total_user/$page_recs);
 if($page_now>$pages){
	$page_now=$pages;
 }
 if($page_now<=1){
	$before_page=1;
	 if($pages>1){
		 $after_page=$page_now+1;
	 }else{
		 $after_page=1;
	 }
 }else{
	$before_page=$page_now-1;
	if($page_now < $pages){
		$after_page=$page_now+1;
	}else{
		$after_page=$pages;
	}
}
$i=($page_now-1)*$page_recs;
$tmpi=0;
if($total_user>0)
mysql_data_seek($rec,$i);
while($row=mysql_fetch_array($rec)){
	$userarray[$tmpi]['pid']=$row['pid'];
    $userarray[$tmpi]['id']=$row['Id'];
    $userarray[$tmpi]['subject']=$row['subject'];
    $userarray[$tmpi]['czyear']=$row['czyear'];
    if(($tmpi+1)%3==0){
    	$userarray[$tmpi]['tr']="<tr></tr>";
    }
    $tmpi++;
	if($tmpi>=$page_recs){
		break;
	}
}
$smarty->assign("types",$types);
$smarty->assign("name",$name);
$smarty->assign('userarray',$userarray);
$smarty->assign("page_now",$page_now);
$smarty->assign("page_recs",$page_recs);
$smarty->assign("pages",$pages);
$smarty->assign("total_user",$total_user);
$smarty->assign("before_page",$before_page);
$smarty->assign("after_page",$after_page);
$smarty->display('img.tpl');
?>